# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Blog Manager

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      FILE_PATH: ${{ secrets.FILE_PATH }}
      GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
    steps:
    - run: echo Done! 🎉

